### ISSUE TITLE
System.NullReferenceException occurred   HResult=0x80004003   Message=Object reference not set to an instance of an object.   Source=CGM.Communication   StackTrace:    at CGM.Communication.MiniMed.MiniMedContext.<StartMultiPacketAsync>d__22.MoveNext() in C:\Dev\CGM.NET\.NET standard\CGM.Communication\MiniMed\MiniMedContext.cs:line 575

### ISSUE THREAD

**Issue by emorrison1962** [cfaagaard/CGM.NET#2]
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CGM.Communication
  StackTrace:
   at CGM.Communication.MiniMed.MiniMedContext.<StartMultiPacketAsync>d__22.MoveNext() in C:\Dev\CGM.NET\.NET standard\CGM.Communication\MiniMed\MiniMedContext.cs:line 575

575   int expectedMessages = Session.PumpDataHistory.CurrentMultiPacketHandler.ExpectedMessages;
CurrentMultiPacketHandler is null.

**Comment by cfaagaard** [comment]
thanks for your input.
I am testing different scenarios with the history/events and different settings. And it looks like the event-bytes is somewhat "shaky" and need more testing. I have uploaded a version where it throws an exception which gets handled in the normal exception handling, in the above scenario. 
If you want to go back to not using events, you just comment out the this [line](https://github.com/cfaagaard/CGM.NET/blob/d4124da80a71d16d8ff5848fbb0d51722b9b04be/.NET%20standard/CGM.Communication/MiniMed/MiniMedContext.cs#L77)

Another thing: I have reached out to the Tidepool project and got a contact. So right now I am testing their API for uploading data directly from CGM.NET.

**Comment by cfaagaard** [comment]
the "construction zone" right now is [this](https://github.com/cfaagaard/CGM.NET/blob/master/.NET%20standard/CGM.Communication/Common/Serialize/MultiPacketHandler.cs).
I test different parameters/setting for the event bytes. And it is not finished.

**Comment by emorrison1962** [comment]
Understood. I saw the "ready for QA" checkin, and assumed it was complete.

Keep up the good work!

Eric.

**Comment by cfaagaard** [comment]
Thanks. 

QA: Yeah, I know.... QA for me (in this project) means that I deploy the UWP application to my Raspberry Pi and let it do its work... and then I do some QA/testing on the logfiles it generates. (Sort of put it into "production" and see what happens.... :-) )

**Comment by cfaagaard** [comment]
Can I close this.

**Comment by emorrison1962** [comment]
Yes.

On Aug 15, 2017 3:10 AM, "cfaagaard" <notifications@github.com> wrote:

Can I close this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cfaagaard/CGM.NET/issues/2#issuecomment-322406153>, or mute
the thread
