### ISSUE TITLE
082117: Build errors....

### ISSUE THREAD

**Issue by emorrison1962** [cfaagaard/CGM.NET#3]
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: CGM.Communication, Configuration: Debug Any CPU ------
1>Common\Serialize\SegementHandler.cs(10,7,10,35): warning CS0105: The using directive for 'CGM.Communication.Extensions' appeared previously in this namespace
1>Data\Repository\PumpRepository.cs(82,27,82,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Data\Repository\NightscoutRepository.cs(29,27,29,44): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Data\Nightscout\UploadLogic.cs(241,28,241,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Extensions\ByteExtension.cs(49,17,49,25): warning CS0219: The variable 'KEY_SIZE' is assigned but its value is never used
1>CGM.Communication -> C:\Dev\CGM.NET\.NET standard\CGM.Communication\bin\Debug\netstandard1.4\CGM.Communication.dll
1>Successfully created package 'C:\Dev\CGM.NET\.NET standard\CGM.Communication\bin\Debug\CGM.Communication.1.0.0.nupkg'.
1>Done building project "CGM.Communication.csproj".
2>------ Skipped Rebuild All: Project: CGM.Uwp, Configuration: Debug x86 ------
2>Project not selected to build for this solution configuration 
3>------ Rebuild All started: Project: CGM.Uwp.BackgroundTask, Configuration: Debug Any CPU ------
3>C:\Dev\CGM.NET\CGM.Uwp.BackgroundTask\Nightscout.cs(6,7,6,15): error CS0246: The type or namespace name 'GalaSoft' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Dev\CGM.NET\CGM.Uwp.BackgroundTask\Nightscout.cs(15,15,15,21): error CS0234: The type or namespace name 'Models' does not exist in the namespace 'CGM.Uwp' (are you missing an assembly reference?)
3>C:\Dev\CGM.NET\CGM.Uwp.BackgroundTask\Nightscout.cs(50,32,50,46): error CS0246: The type or namespace name 'BayerUsbDevice' could not be found (are you missing a using directive or an assembly reference?)
========== Rebuild All: 1 succeeded, 1 failed, 1 skipped ==========

**Comment by cfaagaard** [comment]
hmmmm... sometimes I do not understand github..... well, I have removed the backgroundtask-project and it should build now.

**Comment by emorrison1962** [comment]
This is fixed.
