### ISSUE TITLE
082317: PUMP_DATA communication issue.

### ISSUE THREAD

**Issue by emorrison1962** [cfaagaard/CGM.NET#7]
Christian, 
Thanks for the unit test! That's helpful.

Okay, today I was seeing CommunicationBlock timeout issues. I changed the default value from 5 to randomly, 20, and stopped getting the timeouts.
What I'm seeing now are these errors:
8/23/2017 7:10:36 PM; PUMP_DATA: Block payload size is not a multiple of 2048 (32752 -> -16)
add...
8/23/2017 7:09:18 PM; PUMP_DATA: CRC16CCITT does not match.
...although not in the same session.

NOTE: We may have to find a more private way to exchange log files.
I've got a github repo, but not a paid one. :(

**Comment by cfaagaard** [comment]
Yes I am testing this at the moment. The history comes in a x number of messages. Each messages has a number. Sometimes a number/message is skipped and the CNL never receive that number. So you have to request a resend. It is the last part I am testing right now.
It is the missing messages that causes the errors you are seeing. Sometimes you get lucky and you get all the messages.

**Comment by cfaagaard** [comment]
you are right about our logfiles. I have downloaded yours and edited your comment and deleted the link. (hope that is ok with you)

**Comment by cfaagaard** [comment]
This should be fixed now. There was a major bug in the serializer. (still testing the history when getting over 5 days of history. Should be done this week)
