### ISSUE TITLE
Issues with installing on Pi 3 B+

### ISSUE THREAD

**Issue by macdaddy8000** [cfaagaard/CGM.NET#8]
Hi there, i have been trying to get the CGM to run on my new Pi 3 B+ running Win10 IOT version 10.0.17763.1 but the only thing that happens when i run the code from visual studio on my Pi is that a grey square with a grey X inside appear and then it turns to black screen untill i stop running the app in visual studio, can you help. 

ps. we can write in danish if easier.

**Comment by cfaagaard** [comment]
Hi @macdaddy8000, thanks for trying out the cgm.net. 
There is no UI in the UWP project, so the grey x is the UI :-) . 
If you debug from visual studio you can see the communication log in the debug-window in visual studio. The communication log is also logged in text files.
Is the data uploaded to nightscout?

Have you followed the wiki: https://github.com/cfaagaard/CGM.NET/wiki/Setup-for-Raspberry-PI-3

**Comment by macdaddy8000** [comment]
Okay and it normal that the Square dissappears after 30 seconds? 
Q: When i plug in the Contour Next Link in to the USB on my Raspberry Pi it just starts to recharge, shouldnt it go in data mode?
And is it normal when loading the project into Visual Studio it says this:
![2019-02-03](https://user-images.githubusercontent.com/32962836/52183217-193f3b80-2806-11e9-8994-5f41803c89c8.png)

**Comment by cfaagaard** [comment]
@macdaddy8000 project-loading: I think it is the unittest-project you can't load. I think your are missing installing unittest-capabilities for visual studio.
CNL-datamode: this is normal. The program sets the CNL into data mode when it needs to get the data from the pump.

**Comment by cfaagaard** [comment]
@macdaddy8000 You could try the debug the Console-project first and plugin the CNL into your computer to see if everything is working or the unittest. And then move on to the UWP/PI setup.
