### ISSUE TITLE
Install on Raspberry PI 3B+ url and token question

### ISSUE THREAD

**Issue by Raffytje** [cfaagaard/CGM.NET#9]
Hi,

In the explination on "https://github.com/cfaagaard/CGM.NET/wiki/Setup-for-Raspberry-PI-3" there is at step 5 that you need to enter the nightscout-url / api-secret key. But i cannot find where and how i need to do this.

Can you explain where i need to put this information into the project?

Regards,
Ferry

**Comment by cfaagaard** [comment]
Hi, 
It is in the code.

https://github.com/cfaagaard/CGM.NET/blob/817a4427fbd1996335075348750c2f0d1b26ee35/DataLogger/CGM.Console/Program.cs#L47
Or here
https://github.com/cfaagaard/CGM.NET/blob/817a4427fbd1996335075348750c2f0d1b26ee35/DataLogger/CGM.Uwp/MainPage.xaml.cs#L52

**Comment by Raffytje** [comment]
Hi,

Thanks for the quick response! I will test this later this week. 

Regards,
Ferry
